In [15]:
# python 的原生套件

import os

# 顯示當前路徑
print(os.getcwd())
# location = os.getcwd()
print(os.listdir())

print("="*50)

import sys
print(sys.path) # 顯示存放套件的位置是那些
print(sys.version) # 顯示版本資訊

print("="*50)

# 若想產生隨機數，可以使用random的套件
import random
print(random.random())
print(random.randint(1,10))
print(random.sample("This is a book.", 4))

# 隨機產生10個小數
for i in range(10):
    print (random.random())
    
print("="*50)

# 若想要取出工作目錄的資料夾......
# 除了取用套件外，也可以自己手key
location = os.getcwd()
print(location)
print(type(location))
print(os.path.dirname(location))
print("\\".join(location.split("\\")[0:2]))
# "\\"叫做跳脫字元

C:\Users\車良靜\Desktop\博三下\國家補助python基礎課程\jupyter-notebook-code
['.ipynb_checkpoints', '20190502 Python基礎教學.ipynb', '20190508 資料型別2-1 & 迴圈.ipynb', '20190509 檔案讀寫 & 函式.ipynb', '20190509test1.txt', '20190509test2.txt', '20190509test3.txt', '20190509_sample.csv', '20190516 套件.ipynb']
==================================================
['', 'C:\\Users\\車良靜\\Desktop\\博三下\\國家補助python基礎課程\\jupyter-notebook-code', 'C:\\Anaconda\\python37.zip', 'C:\\Anaconda\\DLLs', 'C:\\Anaconda\\lib', 'C:\\Anaconda', 'C:\\Users\\車良靜\\AppData\\Roaming\\Python\\Python37\\site-packages', 'C:\\Anaconda\\lib\\site-packages', 'C:\\Anaconda\\lib\\site-packages\\win32', 'C:\\Anaconda\\lib\\site-packages\\win32\\lib', 'C:\\Anaconda\\lib\\site-packages\\Pythonwin', 'C:\\Anaconda\\lib\\site-packages\\IPython\\extensions', 'C:\\Users\\車良靜\\.ipython']
3.7.0 (default, Jun 28 2018, 08:04:48) [MSC v.1912 64 bit (AMD64)]
==================================================
0.572840776599131
4
['h', 'o', 'k', 'i']
0.6745561628221511
0.569750362244576
0.3065892316901352
0.9787657325412874
0.3026437487774998
0.6400061878783654
0.3278274270204873
0.9200493461181976
0.9093987003197976
0.10982713643423114
==================================================
C:\Users\車良靜\Desktop\博三下\國家補助python基礎課程\jupyter-notebook-code
<class 'str'>
C:\Users\車良靜\Desktop\博三下\國家補助python基礎課程
C:\Users

In [10]:
pip install pandas

The following command must be run outside of the IPython shell:

    $ pip install pandas

The Python package manager (pip) can only be used from outside of IPython.
Please reissue the `pip` command in a separate terminal or command prompt.

See the Python documentation for more information on how to install packages:

    https://docs.python.org/3/installing/

## pandas套件

### pandas使用
* **創造DataFrame**：pd.DataFrame(list)
* **讀取資料**：pd.read_csv(...)/pd.read.json(...)
* **選擇特定欄位資料**：df = pd.read_csv(...); pd["column_name"]
* **造新欄位**：df["column name"] = df["old_column"]
(ex: df["重量磅" = df ["重量(磅)"]=df["重量"/1000])
* **過濾資料(將條件放入)**：df(condition)
(ex: df[df["國家"] == "日本"]，裡面的df意思是從DataFrame裡面判斷國家是日本的欄位，外面的df意思是再把符合條件的項目丟回原先的DataFrame並顯示出符合條件的欄位)

In [37]:
import pandas as pd

data = [
    {"Name":"Jeff", "Age":18, "Gender":"M"},
    {"Name":"Lilian", "Age":24, "Gender":"F"},
    {"Name":"Eve", "Age":12, "Gender":"F"},
]

# 用pandas讀取的資料呈現方式是DataFrame
# 創造DataFrame
df1 = pd.DataFrame(data)
df1

   Age Gender    Name
0   18      M    Jeff
1   24      F  Lilian
2   12      F     Eve

In [38]:
# 從外部讀取檔案
print(os.listdir())
with open("20190509_sample.csv", "r", encoding = "utf-8") as inFile:
    data2 = inFile.readlines()
print(data2)

['.ipynb_checkpoints', '20190502 Python基礎教學.ipynb', '20190508 資料型別2-1 & 迴圈.ipynb', '20190509 檔案讀寫 & 函式.ipynb', '20190509test1.txt', '20190509test2.txt', '20190509test3.txt', '20190509_sample.csv', '20190516 套件.ipynb']
['貨品分類,中文貨名,英文貨名,國家,數量,數量單位,重量,重量單位,價值\n', '3032300007,冷凍吳郭魚," Tilapias, frozen",巴林,0,-   ,8000,KGM ,411\n', '3032300007,冷凍吳郭魚," Tilapias, frozen",日本,0,-   ,10800,KGM ,696\n', '3032300007,冷凍吳郭魚," Tilapias, frozen",加拿大,0,-   ,108631,KGM ,7365\n', '3032300007,冷凍吳郭魚," Tilapias, frozen",沙烏地阿拉伯,0,-   ,503000,KGM ,24919\n', '3032300007,冷凍吳郭魚," Tilapias, frozen",其他大洋洲國家,0,-   ,11695,KGM ,729\n', '3032300007,冷凍吳郭魚," Tilapias, frozen",阿拉伯聯合大公國,0,-   ,29000,KGM ,1274\n', '3032300007,冷凍吳郭魚," Tilapias, frozen",科威特,0,-   ,121536,KGM ,6128\n', '3032300007,冷凍吳郭魚," Tilapias, frozen",美國,0,-   ,749982,KGM ,46022\n', '3032300007,冷凍吳郭魚," Tilapias, frozen",香港,0,-   ,72,KGM ,2\n', '3032300007,冷凍吳郭魚," Tilapias, frozen",澳大利亞,0,-   ,69570,KGM ,4786\n', '3032300007,冷凍吳郭魚," Tilapias, frozen",關島,0,-   ,8618,KGM ,458\n', '12019000104,黑豆，不論是否破碎," Black soybeans, whether or not broken",加拿大,0,-   ,0,TNE ,43\n', '12019000104,黑豆，不論是否破碎," Black soybeans, whether or not broken",美國,0,-   ,0,TNE ,9\n', '12019000104,黑豆，不論是否破碎," Black soybeans, whether or not broken",菲律賓,0,-   ,0,TNE ,6\n', '52114200005,牛仔布, Denim,中國大陸,11398,MTK ,1991,KGM ,902\n', '52114200005,牛仔布, Denim,日本,14364,MTK ,3898,KGM ,1596\n', '52114200005,牛仔布, Denim,印尼,21998,MTK ,3869,KGM ,1543\n', '52114200005,牛仔布, Denim,印度,7212,MTK ,2185,KGM ,513\n', '52114200005,牛仔布, Denim,柬埔寨,28081,MTK ,9915,KGM ,2469\n', '52114200005,牛仔布, Denim,馬來西亞,8925,MTK ,3598,KGM ,575\n', '52114200005,牛仔布, Denim,越南,139191,MTK ,53225,KGM ,12330\n', '52114200005,牛仔布, Denim,賴索托,6894,MTK ,2771,KGM ,435\n']

In [39]:
# 將外部檔案轉成DataFrame
df2 = pd.DataFrame(data2)
df2

                                                    0
0              貨品分類,中文貨名,英文貨名,國家,數量,數量單位,重量,重量單位,價值\n
1   3032300007,冷凍吳郭魚," Tilapias, frozen",巴林,0,-   ...
2   3032300007,冷凍吳郭魚," Tilapias, frozen",日本,0,-   ...
3   3032300007,冷凍吳郭魚," Tilapias, frozen",加拿大,0,-  ...
4   3032300007,冷凍吳郭魚," Tilapias, frozen",沙烏地阿拉伯,0,...
5   3032300007,冷凍吳郭魚," Tilapias, frozen",其他大洋洲國家,0...
6   3032300007,冷凍吳郭魚," Tilapias, frozen",阿拉伯聯合大公國,...
7   3032300007,冷凍吳郭魚," Tilapias, frozen",科威特,0,-  ...
8   3032300007,冷凍吳郭魚," Tilapias, frozen",美國,0,-   ...
9   3032300007,冷凍吳郭魚," Tilapias, frozen",香港,0,-   ...
10  3032300007,冷凍吳郭魚," Tilapias, frozen",澳大利亞,0,- ...
11  3032300007,冷凍吳郭魚," Tilapias, frozen",關島,0,-   ...
12  12019000104,黑豆，不論是否破碎," Black soybeans, whethe...
13  12019000104,黑豆，不論是否破碎," Black soybeans, whethe...
14  12019000104,黑豆，不論是否破碎," Black soybeans, whethe...
15  52114200005,牛仔布, Denim,中國大陸,11398,MTK ,1991,KG...
16  52114200005,牛仔布, Denim,日本,14364,MTK ,3898,KGM ...
17  52114200005,牛仔布, Denim,印尼,21998,MTK ,3869,KGM ...
18  52114200005,牛仔布, Denim,印度,7212,MTK ,2185,KGM ,...
19  52114200005,牛仔布, Denim,柬埔寨,28081,MTK ,9915,KGM...
20  52114200005,牛仔布, Denim,馬來西亞,8925,MTK ,3598,KGM...
21  52114200005,牛仔布, Denim,越南,139191,MTK ,53225,KG...
22  52114200005,牛仔布, Denim,賴索托,6894,MTK ,2771,KGM ...

In [42]:
# 直接以DataFrame的方式讀取資料
df3 = pd.read_csv("20190509_sample.csv")
df3

,貨品分類,中文貨名,英文貨名,國家,數量,數量單位,重量,重量單位,價值
0,3032300007,冷凍吳郭魚,"Tilapias, frozen",巴林,0,-,8000,KGM,411
1,3032300007,冷凍吳郭魚,"Tilapias, frozen",日本,0,-,10800,KGM,696
2,3032300007,冷凍吳郭魚,"Tilapias, frozen",加拿大,0,-,108631,KGM,7365
3,3032300007,冷凍吳郭魚,"Tilapias, frozen",沙烏地阿拉伯,0,-,503000,KGM,24919
4,3032300007,冷凍吳郭魚,"Tilapias, frozen",其他大洋洲國家,0,-,11695,KGM,729
5,3032300007,冷凍吳郭魚,"Tilapias, frozen",阿拉伯聯合大公國,0,-,29000,KGM,1274
6,3032300007,冷凍吳郭魚,"Tilapias, frozen",科威特,0,-,121536,KGM,6128
7,3032300007,冷凍吳郭魚,"Tilapias, frozen",美國,0,-,749982,KGM,46022
8,3032300007,冷凍吳郭魚,"Tilapias, frozen",香港,0,-,72,KGM,2
9,3032300007,冷凍吳郭魚,"Tilapias, frozen",澳大利亞,0,-,69570,KGM,4786
10,3032300007,冷凍吳郭魚,"Tilapias, frozen",關島,0,-,8618,KGM,458
11,12019000104,黑豆，不論是否破碎,"Black soybeans, whether or not broken",加拿大,0,-,0,TNE,43
12,12019000104,黑豆，不論是否破碎,"Black soybeans, whether or not broken",美國,0,-,0,TNE,9
13,12019000104,黑豆，不論是否破碎,"Black soybeans, whether or not broken",菲律賓,0,-,0,TNE,6
14,52114200005,牛仔布,Denim,中國大陸,11398,MTK,1991,KGM,902
15,52114200005,牛仔布,Denim,日本,14364,MTK,3898,KGM,1596
16,52114200005,牛仔布,Denim,印尼,21998,MTK,3869,KGM,1543
17,52114200005,牛仔布,Denim,印度,7212,MTK,2185,KGM,513
18,52114200005,牛仔布,Denim,柬埔寨,28081,MTK,9915,KGM,2469
19,52114200005,牛仔布,Denim,馬來西亞,8925,MTK,3598,KGM,575
20,52114200005,牛仔布,Denim,越南,139191,MTK,53225,KGM,12330
21,52114200005,牛仔布,Denim,賴索托,6894,MTK,2771,KGM,435

In [46]:
# 選擇特定欄位資料
df3["國家"]

0           巴林
1           日本
2          加拿大
3       沙烏地阿拉伯
4      其他大洋洲國家
5     阿拉伯聯合大公國
6          科威特
7           美國
8           香港
9         澳大利亞
10          關島
11         加拿大
12          美國
13         菲律賓
14        中國大陸
15          日本
16          印尼
17          印度
18         柬埔寨
19        馬來西亞
20          越南
21         賴索托
Name: 國家, dtype: object

In [60]:
# 造新欄位

df3["價值(NTD)"] = df3["價值"]*31
# 選擇中文貨名欄位中前兩個字，並增加在最後一列中

# 寫成 df3["中文貨名(首兩字)"] = df3 ["中文貨名"][0:2]會出現不同的結果
# 需要將字串進行轉換，才能提取出每一列中的前兩個中文字
df3["中文貨名(首兩字)"] = df3 ["中文貨名"].str[0:2]
df3

,貨品分類,中文貨名,英文貨名,國家,數量,數量單位,重量,重量單位,價值,價值(NTD),中文貨名(首兩字)
0,3032300007,冷凍吳郭魚,"Tilapias, frozen",巴林,0,-,8000,KGM,411,12741,冷凍
1,3032300007,冷凍吳郭魚,"Tilapias, frozen",日本,0,-,10800,KGM,696,21576,冷凍
2,3032300007,冷凍吳郭魚,"Tilapias, frozen",加拿大,0,-,108631,KGM,7365,228315,冷凍
3,3032300007,冷凍吳郭魚,"Tilapias, frozen",沙烏地阿拉伯,0,-,503000,KGM,24919,772489,冷凍
4,3032300007,冷凍吳郭魚,"Tilapias, frozen",其他大洋洲國家,0,-,11695,KGM,729,22599,冷凍
5,3032300007,冷凍吳郭魚,"Tilapias, frozen",阿拉伯聯合大公國,0,-,29000,KGM,1274,39494,冷凍
6,3032300007,冷凍吳郭魚,"Tilapias, frozen",科威特,0,-,121536,KGM,6128,189968,冷凍
7,3032300007,冷凍吳郭魚,"Tilapias, frozen",美國,0,-,749982,KGM,46022,1426682,冷凍
8,3032300007,冷凍吳郭魚,"Tilapias, frozen",香港,0,-,72,KGM,2,62,冷凍
9,3032300007,冷凍吳郭魚,"Tilapias, frozen",澳大利亞,0,-,69570,KGM,4786,148366,冷凍
10,3032300007,冷凍吳郭魚,"Tilapias, frozen",關島,0,-,8618,KGM,458,14198,冷凍
11,12019000104,黑豆，不論是否破碎,"Black soybeans, whether or not broken",加拿大,0,-,0,TNE,43,1333,黑豆
12,12019000104,黑豆，不論是否破碎,"Black soybeans, whether or not broken",美國,0,-,0,TNE,9,279,黑豆
13,12019000104,黑豆，不論是否破碎,"Black soybeans, whether or not broken",菲律賓,0,-,0,TNE,6,186,黑豆
14,52114200005,牛仔布,Denim,中國大陸,11398,MTK,1991,KGM,902,27962,牛仔
15,52114200005,牛仔布,Denim,日本,14364,MTK,3898,KGM,1596,49476,牛仔
16,52114200005,牛仔布,Denim,印尼,21998,MTK,3869,KGM,1543,47833,牛仔
17,52114200005,牛仔布,Denim,印度,7212,MTK,2185,KGM,513,15903,牛仔
18,52114200005,牛仔布,Denim,柬埔寨,28081,MTK,9915,KGM,2469,76539,牛仔
19,52114200005,牛仔布,Denim,馬來西亞,8925,MTK,3598,KGM,575,17825,牛仔
20,52114200005,牛仔布,Denim,越南,139191,MTK,53225,KGM,12330,382230,牛仔
21,52114200005,牛仔布,Denim,賴索托,6894,MTK,2771,KGM,435,13485,牛仔

In [63]:
# 造新欄位 part2

# 直接加入新值
df3["數量單位2"] = "!!!"
df3

,貨品分類,中文貨名,英文貨名,國家,數量,數量單位,重量,重量單位,價值,價值(NTD),中文貨名(首兩字),數量單位2
0,3032300007,冷凍吳郭魚,"Tilapias, frozen",巴林,0,-,8000,KGM,411,12741,冷凍,!!!
1,3032300007,冷凍吳郭魚,"Tilapias, frozen",日本,0,-,10800,KGM,696,21576,冷凍,!!!
2,3032300007,冷凍吳郭魚,"Tilapias, frozen",加拿大,0,-,108631,KGM,7365,228315,冷凍,!!!
3,3032300007,冷凍吳郭魚,"Tilapias, frozen",沙烏地阿拉伯,0,-,503000,KGM,24919,772489,冷凍,!!!
4,3032300007,冷凍吳郭魚,"Tilapias, frozen",其他大洋洲國家,0,-,11695,KGM,729,22599,冷凍,!!!
5,3032300007,冷凍吳郭魚,"Tilapias, frozen",阿拉伯聯合大公國,0,-,29000,KGM,1274,39494,冷凍,!!!
6,3032300007,冷凍吳郭魚,"Tilapias, frozen",科威特,0,-,121536,KGM,6128,189968,冷凍,!!!
7,3032300007,冷凍吳郭魚,"Tilapias, frozen",美國,0,-,749982,KGM,46022,1426682,冷凍,!!!
8,3032300007,冷凍吳郭魚,"Tilapias, frozen",香港,0,-,72,KGM,2,62,冷凍,!!!
9,3032300007,冷凍吳郭魚,"Tilapias, frozen",澳大利亞,0,-,69570,KGM,4786,148366,冷凍,!!!
10,3032300007,冷凍吳郭魚,"Tilapias, frozen",關島,0,-,8618,KGM,458,14198,冷凍,!!!
11,12019000104,黑豆，不論是否破碎,"Black soybeans, whether or not broken",加拿大,0,-,0,TNE,43,1333,黑豆,!!!
12,12019000104,黑豆，不論是否破碎,"Black soybeans, whether or not broken",美國,0,-,0,TNE,9,279,黑豆,!!!
13,12019000104,黑豆，不論是否破碎,"Black soybeans, whether or not broken",菲律賓,0,-,0,TNE,6,186,黑豆,!!!
14,52114200005,牛仔布,Denim,中國大陸,11398,MTK,1991,KGM,902,27962,牛仔,!!!
15,52114200005,牛仔布,Denim,日本,14364,MTK,3898,KGM,1596,49476,牛仔,!!!
16,52114200005,牛仔布,Denim,印尼,21998,MTK,3869,KGM,1543,47833,牛仔,!!!
17,52114200005,牛仔布,Denim,印度,7212,MTK,2185,KGM,513,15903,牛仔,!!!
18,52114200005,牛仔布,Denim,柬埔寨,28081,MTK,9915,KGM,2469,76539,牛仔,!!!
19,52114200005,牛仔布,Denim,馬來西亞,8925,MTK,3598,KGM,575,17825,牛仔,!!!
20,52114200005,牛仔布,Denim,越南,139191,MTK,53225,KGM,12330,382230,牛仔,!!!
21,52114200005,牛仔布,Denim,賴索托,6894,MTK,2771,KGM,435,13485,牛仔,!!!

In [69]:
# 過濾資料

df3["國家"] == "日本"

0     False
1      True
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15     True
16    False
17    False
18    False
19    False
20    False
21    False
Name: 國家, dtype: bool

In [81]:
class Person:
    def __init__(self,name,age):
        self.name = name
        self.age = age
    def sayMyName(self):
        print("HiHi!My name is {}.".format(self.name))
# person1 和 person2 都是一個物件
## 物件 = 類別 產生()
person1 = Person("Lilian", 18)
person2 = Person("Eve", 16)

# 呼叫屬性
print(person1.name)
print(person2.age) 

print("="*50)

print(person1.sayMyName())
print(person)

Lilian
16
==================================================
HiHi!My name is Lilian.
None

### 小試身手

#### 試撰寫一個class為Student
#### 靜態屬性包含：standard = 70
#### 屬性包含：name(str)，studNo(int), grades(list)
#### 函式包含：
    * avg：回傳grades list的平均值
    * add(grade)：新增成績到grades list中，並顯示grades狀態
    * failedCount()：回傳不及格(<standard)總數

In [ ]:
class Student:
    standard = 70
    def __init__(self, name, studNo, grades, standard):
        self.name = name
        self.studNo = studNo
        self.grades = grades
        self.standard = standard
    def avg(self):
        return sum(self.grades)/3
    
    
    
    def failedCount(self):
        result = []  # 先準備一個空陣列
        for score in self.grades:
            if score < Student.standard:
                result.append(score)
        return len(result)

In [ ]:
# 試跑資料
s1 = Student("Kevin", 1001, [90,50,35])
s2 = Student("Jenny", 1002, [72,84,99])

#s1.avg
#s2.avg

#### self其實就是物件本身，可以想成就是s1與s2